apiVersion: v1
kind: Service
metadata:
  name: image-api
  namespace: image-pipeline
spec:
  type: NodePort
  selector:
    app: image-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001

